In [1]:
# Numpy

In [ ]:
Ndarray
Creating Ndarrays
    1-D
    2-D
    3-D

ndim attribute
shape attribute

### Indexing and slicing in numpy array

In [2]:
# 1-D ndarry indexing


In [4]:
import numpy as np


arr1 = np.array([12, 34, 45, 67, 78, 45, 56, 34])

In [ ]:
# syntex
    # objectname[indexnumber]

In [5]:
arr1[3]

67

In [6]:
arr1[6]

56

In [7]:
arr1[-2]

56

In [ ]:
# 2-D ndarray Indexing

In [8]:
arr2 = np.array([[12, 34, 45, 56, 78, 34], [45, 56, 67, 7, 8, 100]])

In [9]:
arr2.ndim

2

In [10]:
arr2

array([[ 12,  34,  45,  56,  78,  34],
       [ 45,  56,  67,   7,   8, 100]])

In [11]:
# syntex
# objectname[rownumber][indexnumber]

In [13]:
arr2[1][2]

67

In [14]:
arr2 = np.array([[12, 34, 45, 56, 78, 34], [45, 56, 67, 7, 8, 100]])

In [16]:
arr2[1][3]

7

In [17]:
arr2[0][2]

45

In [18]:
# indexing with 3d Data

In [19]:
arr4 = np.array([[[23, 4, 67], [45, 56, 7]], [[89, 90, 78], [89, 78, 34]]])

In [20]:
arr4.ndim

3

In [23]:
arr4[1][1][1]

78

In [24]:
arr4[0][1][2]

7

In [31]:
arr4 = np.array([[[23, 4, 67], [45, 56, 7]], [[89, 90, 78],  [89, 78, 34]], [[45, 67, 89],  [56, 34, 444]]])

In [27]:
arr4

array([[[23,  4, 67],
        [45, 56,  7]],

       [[89, 90, 78],
        [89, 78, 34]],

       [[45, 67, 89],
        [56, 34, 23]]])

In [28]:
arr4.ndim

3

In [32]:
arr4[2][1][2]

444

# Slicing

objectname[startindex : endindexnumber : increment]

defult values:
    start : 0
    end : n - 1
    increment : 1

In [33]:
zx = np.array([3, 45, 56, 78, 45, 34, 56, 34, 23])

In [35]:
zx[3 : 8 : 1]

array([78, 45, 34, 56, 34])

In [36]:
zx[3 : 8]

array([78, 45, 34, 56, 34])

In [37]:
zx[1 : 5]

array([45, 56, 78, 45])

In [38]:
zx = np.array([3, 45, 56, 78, 45, 34, 56, 34, 23])

In [39]:
zx[2 : ]

array([56, 78, 45, 34, 56, 34, 23])

In [40]:
zx[ : 5]

array([ 3, 45, 56, 78, 45])

In [41]:
zx = np.array([3, 45, 56, 78, 45, 34, 56, 34, 23])

In [43]:
zx[: : 2]

array([ 3, 56, 45, 56, 23])

In [44]:
zx[: : -1]

array([23, 34, 56, 34, 45, 78, 56, 45,  3])

In [45]:
# 2-D slicing

In [46]:
zx = np.array([[34, 45, 67, 45, 34, 45, 56], [45, 34, 23, 4, 5, 56, 34]])

In [47]:
zx.ndim

2

In [49]:
zx[1][1 : 5]

array([34, 23,  4,  5])

In [50]:
zx[0][4 : ]

array([34, 45, 56])

In [51]:
# slcing with 3-d

In [52]:
arr4 = np.array([[[23, 4, 67], [45, 56, 7]], [[89, 90, 78],  [89, 78, 34]], [[45, 67, 89],  [56, 34, 444]]])

In [53]:
arr4[2][0][1:]

array([67, 89])

In [56]:
arr4[2][0][: 2]

array([45, 67])