In [ ]:
# Numpy
# Ndarrays
# demmensions
#     1d, 2d, 3d

# ndim
# shape

# indexing
# slicing

In [1]:
import numpy as np

In [2]:
arr = np.array([12, 23, 4, 56, 67, 89])

In [3]:
# adding new elemt in ndarray

In [4]:
# append() -->

In [5]:
# np.append(objectname, element)

In [6]:
arr

array([12, 23,  4, 56, 67, 89])

In [9]:
xyz = np.append(arr, 100)

In [10]:
xyz

array([ 12,  23,   4,  56,  67,  89, 100])

In [11]:
# insert()

In [12]:
# np.insert(objctname, indexnumber, element)

In [13]:
xyz = np.array([3, 45, 56, 67, 45, 34, 45, 234, 12])

In [14]:
np.insert(xyz, 2, 100)

array([  3,  45, 100,  56,  67,  45,  34,  45, 234,  12])

In [15]:
np.insert(xyz, 2, [23, 45, 56])

array([  3,  45,  23,  45,  56,  56,  67,  45,  34,  45, 234,  12])

In [16]:
abc = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [17]:
index_number = [1, 4, 7]

elements = [100, 200, 300]

In [18]:
np.insert(abc, index_number, elements)

array([  1, 100,   2,   3,   4, 200,   5,   6,   7, 300,   8,   9,  10])

In [19]:
np.insert(abc, [1, 4, 7], [100, 200, 300])

array([  1, 100,   2,   3,   4, 200,   5,   6,   7, 300,   8,   9,  10])

In [20]:
# replacing elements / update

In [22]:
arr3 = np.array([23, 34, 45, 56, 67, 78, 10])

In [23]:
# objectname[indexnumber] = new_element

In [24]:
arr3[2] = 100

In [25]:
arr3

array([ 23,  34, 100,  56,  67,  78,  10])

In [26]:
arr3 = np.array([23, 34, 45, 56, 67, 78, 10])

In [27]:
arr3[[1, 4, -1]] = [100, 200, 300]

In [28]:
arr3

array([ 23, 100,  45,  56, 200,  78, 300])

In [29]:
# deleteing elements from ndarray


In [30]:
arr3 = np.array([23, 34, 45, 56, 67, 78, 10])

In [31]:
# np.delete(objectname, indexnumber)

In [33]:
np.delete(arr3, -1)

array([23, 34, 45, 56, 67, 78])

In [34]:
np.delete(arr3, [1, 4, -1])

array([23, 45, 56, 78])

In [ ]:
append
insert
elements replace
delete