In [ ]:
# Numpy


# random

# python ---- random
# numpy ----- random

In [1]:
import numpy as np
from numpy import random

In [2]:
# randint() ----->

In [8]:
zx = random.randint(100)

zx

63

In [12]:
zx = random.randint(10, 30)
zx

26

In [13]:
# size ----> perameter

In [14]:
# 10 ---- 50   ::: 5

In [15]:
zx = random.randint(10, 20, size = (5))
zx

array([16, 19, 15, 11, 12])

In [16]:
zx = random.randint(11, 50, size = (3, 4))
zx

array([[36, 42, 22, 44],
       [40, 14, 30, 49],
       [27, 49, 43, 19]])

In [17]:
pq = random.randint(1, 5, size = (3, 4, 3))
pq

array([[[4, 3, 1],
        [2, 3, 3],
        [4, 3, 4],
        [2, 3, 3]],

       [[1, 3, 1],
        [2, 3, 2],
        [4, 3, 4],
        [1, 1, 4]],

       [[2, 3, 3],
        [1, 2, 2],
        [1, 3, 4],
        [1, 1, 1]]])

In [ ]:
# randint() ----> genrate elemets from a spacific range

# randint(start, end, size = (demminsiosn))

In [18]:
# rand()  -----> 0 to 1

In [23]:
x = random.rand()
x

0.35485617848927276

In [25]:
x = random.rand(10)
x

array([0.47102806, 0.51125764, 0.71861203, 0.77059635, 0.80316403,
       0.36419875, 0.68111973, 0.99147324, 0.23933938, 0.095869  ])

In [26]:
x = random.rand(4, 5)
x

array([[0.83260282, 0.99996877, 0.70515089, 0.61905541, 0.95713644],
       [0.74745952, 0.43751416, 0.73012575, 0.84956504, 0.09734694],
       [0.08620697, 0.02211861, 0.07291368, 0.52130915, 0.90344816],
       [0.93308985, 0.54491932, 0.38114777, 0.26284802, 0.04802345]])

In [27]:
# random()

In [33]:
pq = random.random()
pq

0.2908586372094424

In [34]:
# choice()

In [42]:
zx = random.choice([1, 5, 3, 4, 2, 6])
zx

4

In [43]:
zx = random.choice([1, 5, 3, 4, 2, 6], size = 4)
zx

array([3, 2, 4, 5])

In [44]:
zx = random.choice([1, 5, 3, 4, 2, 6], size = (3, 5))
zx

array([[5, 5, 1, 4, 2],
       [4, 1, 5, 3, 1],
       [1, 6, 3, 1, 6]])

In [45]:
# random.shuffle() ---->

In [56]:
zx = np.array([1, 2, 3, 4, 5, 6, 7, 9])

In [57]:
random.shuffle(zx)

In [58]:
zx

array([6, 2, 7, 4, 9, 3, 1, 5])

In [ ]:
# random()
# randint()
# rand()
# choice()
# shuffle()