In [1]:
import numpy as np

zx = np.array(["cat", "dog", "bird", "cat", "dog", "fish"])

In [2]:
zx

array(['cat', 'dog', 'bird', 'cat', 'dog', 'fish'], dtype='<U4')

In [4]:
x = 0
y = 0
z = 0

for i in zx:
    if i =

cat
dog
bird
cat
dog
fish


In [5]:
zx = np.array([1, 2, 3, 2, 1, 2, 3, 2, 1, 3, 4, 5, 2])

In [6]:
np.unique(zx)

array([1, 2, 3, 4, 5])

In [8]:
pq = {1, 2, 3, 2, 1, 2, 3, 2, 1, 3, 4, 5, 2}
pq

{1, 2, 3, 4, 5}

In [10]:
zx = np.array(["cat", "dog", "bird", "cat", "dog", "fish"])

pq = np.unique(zx)

for i in pq:
    x = 0
    for j in zx:
        if i == j:
            x = x + 1
    print(f"Count of {i} is :", x)

Count of bird is : 1
Count of cat is : 2
Count of dog is : 2
Count of fish is : 1


In [54]:
data = np.arange(1, 101)

In [55]:
df = np.reshape(data, (10, 10))

In [56]:
df

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [57]:
data = df.reshape(-1)

In [58]:
data

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [30]:
index_with_devide_by_2 = np.where(data % 2 == 0)

In [31]:
data[index_with_devide_by_2] = 0

In [32]:
data

array([ 1,  0,  3,  0,  5,  0,  7,  0,  9,  0, 11,  0, 13,  0, 15,  0, 17,
        0, 19,  0, 21,  0, 23,  0, 25,  0, 27,  0, 29,  0, 31,  0, 33,  0,
       35,  0, 37,  0, 39,  0, 41,  0, 43,  0, 45,  0, 47,  0, 49,  0, 51,
        0, 53,  0, 55,  0, 57,  0, 59,  0, 61,  0, 63,  0, 65,  0, 67,  0,
       69,  0, 71,  0, 73,  0, 75,  0, 77,  0, 79,  0, 81,  0, 83,  0, 85,
        0, 87,  0, 89,  0, 91,  0, 93,  0, 95,  0, 97,  0, 99,  0])

In [33]:
data[ np.where(data % 2 != 0)] = 1

In [34]:
data

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [38]:
 np.where(data % 2 == 0 & data % 3 == 0) = 2

SyntaxError: cannot assign to function call here. Maybe you meant '==' instead of '='? (647432740.py, line 1)

In [59]:
q = np.where(data % 2 == 0) and np.where(data % 3 == 0)
q

(array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50,
        53, 56, 59, 62, 65, 68, 71, 74, 77, 80, 83, 86, 89, 92, 95, 98],
       dtype=int64),)

In [60]:
data

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])