In [ ]:
# Numpy : 
#     arrays
#     ndarray
#     slicing
#     indexing
#     ndim
#     shape
#     where ::::::::::::::::
#         CRUD operations

# reshape : this is a method that help us to reshape the shape of data

### 1-D ndarray =-----> 2-D array

In [2]:
import numpy as np

In [4]:
arr = np.array([12, 34, 45, 56, 78, 45, 34, 56, 23])

In [5]:
arr.ndim

1

In [6]:
# reshape()

In [ ]:
# np.reshape(objectname, shape)

# objectname.reshaape(shape)

In [7]:
arr = np.array([12, 34, 45, 56, 78, 45, 34, 56, 23])

In [8]:
np.reshape(arr, (3, 3))

array([[12, 34, 45],
       [56, 78, 45],
       [34, 56, 23]])

In [9]:
arr = np.array([12, 34, 45, 56, 78, 45, 34, 56, 23])

In [10]:
np.reshape(arr, (1, 9))

array([[12, 34, 45, 56, 78, 45, 34, 56, 23]])

In [12]:
qw = np.reshape(arr, (9, 1))

In [13]:
qw.ndim

2

In [14]:
qw

array([[12],
       [34],
       [45],
       [56],
       [78],
       [45],
       [34],
       [56],
       [23]])

# 2d to 1D

In [16]:
zx = np.array([[12, 34, 45, 67, 45, 23], [45, 56, 23, 56, 23, 23]])

In [17]:
zx

array([[12, 34, 45, 67, 45, 23],
       [45, 56, 23, 56, 23, 23]])

In [18]:
zx.ndim

2

In [19]:
zx = np.array([[12, 34, 45, 67, 45, 23], [45, 56, 23, 56, 23, 23]])

In [20]:
np.reshape(zx, (12))

array([12, 34, 45, 67, 45, 23, 45, 56, 23, 56, 23, 23])

In [21]:
# -1

In [22]:
zx = np.array([[12, 34, 45, 67, 45, 23], [45, 56, 23, 56, 23, 23]])

In [23]:
zx

array([[12, 34, 45, 67, 45, 23],
       [45, 56, 23, 56, 23, 23]])

In [24]:
np.reshape(zx, -1)

array([12, 34, 45, 67, 45, 23, 45, 56, 23, 56, 23, 23])

In [25]:
# 1-D to 2-D

In [33]:
arr = np.array([12, 34, 45, 56, 78, 45, 34, 56, 23, 34, 657, 45])

In [36]:
np.reshape(arr, (2, -1))

array([[ 12,  34,  45,  56,  78,  45],
       [ 34,  56,  23,  34, 657,  45]])

In [37]:
arr = np.array([12, 34, 45, 56, 78, 45, 34, 56, 23, 34, 657, 45])

In [40]:
np.reshape(arr, (-1, 6))

array([[ 12,  34,  45,  56,  78,  45],
       [ 34,  56,  23,  34, 657,  45]])

In [41]:
# 1-D to 3-D

In [42]:
arr = np.array([12, 34, 45, 56, 78, 45, 34, 56, 23, 34, 657, 45])

In [43]:
np.reshape(arr, (2, 2, 3))

array([[[ 12,  34,  45],
        [ 56,  78,  45]],

       [[ 34,  56,  23],
        [ 34, 657,  45]]])

In [44]:
zx = np.array([[[23, 45, 23], [45, 56, 34]], [[45, 56, 34], [45, 34, 23]]])

In [45]:
zx

array([[[23, 45, 23],
        [45, 56, 34]],

       [[45, 56, 34],
        [45, 34, 23]]])

In [47]:
zx.ndim

3

In [48]:
np.reshape(zx, -1)

array([23, 45, 23, 45, 56, 34, 45, 56, 34, 45, 34, 23])

In [49]:
# where()

In [50]:
# sort()

In [51]:
xyz = np.array([12, 34, 45, 5, 67, 45, 3, 45, 34])

In [53]:
qw = np.sort(xyz)

In [54]:
qw

array([ 3,  5, 12, 34, 34, 45, 45, 45, 67])

In [55]:
qw[: : -1]

array([67, 45, 45, 45, 34, 34, 12,  5,  3])

In [56]:
# zeros()

In [63]:
zx = np.zeros((5, 3, 4))

In [64]:
zx

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [65]:
pq = np.ones(3)

In [66]:
pq

array([1., 1., 1.])

In [ ]:
np.eye

In [67]:
help(np.eye)

Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
    Return a 2-D array with ones on the diagonal and zeros elsewhere.

    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.

        .. versionadded:: 1.14.0
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_func

In [68]:
x = np.eye(3, 3)

In [69]:
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [70]:
# combining ndarryas

In [72]:
x = np.array([12, 23, 4, 56])

y = np.array([34, 56, 7, 45])

In [73]:
x + y

array([ 46,  79,  11, 101])

In [78]:
x = np.array([12, 23, 4, 56])

y = np.array([34, 56, 7, 45, 45, 34, 2])

In [79]:
# 1) concatenate
# 2) vstack

In [80]:
np.concatenate((x, y))

array([12, 23,  4, 56, 34, 56,  7, 45, 45, 34,  2])

In [81]:
x = np.array([12, 23, 4, 56])
y = np.array([34, 56, 2, 3])

In [82]:
np.vstack((x, y))

array([[12, 23,  4, 56],
       [34, 56,  2,  3]])

In [ ]:
sort()
contactemate()
vstack()
eye()
zeros()
ones()

In [ ]:
# random