In [ ]:
# Numpy : 
#     arrays
#     ndarray
#     slicing
#     indexing
#     ndim
#     shape
#     where
#         CRUD operations

# reshape : this is a method that help us to reshape the shape of data

### 1-D ndarray =-----> 2-D array

In [2]:
import numpy as np

In [4]:
arr = np.array([12, 34, 45, 56, 78, 45, 34, 56, 23])

In [5]:
arr.ndim

1

In [6]:
# reshape()

In [ ]:
# np.reshape(objectname, shape)

# objectname.reshaape(shape)

In [7]:
arr = np.array([12, 34, 45, 56, 78, 45, 34, 56, 23])

In [8]:
np.reshape(arr, (3, 3))

array([[12, 34, 45],
       [56, 78, 45],
       [34, 56, 23]])

In [9]:
arr = np.array([12, 34, 45, 56, 78, 45, 34, 56, 23])

In [10]:
np.reshape(arr, (1, 9))

array([[12, 34, 45, 56, 78, 45, 34, 56, 23]])

In [12]:
qw = np.reshape(arr, (9, 1))

In [13]:
qw.ndim

2

In [14]:
qw

array([[12],
       [34],
       [45],
       [56],
       [78],
       [45],
       [34],
       [56],
       [23]])

# 2d to 1D

In [16]:
zx = np.array([[12, 34, 45, 67, 45, 23], [45, 56, 23, 56, 23, 23]])

In [17]:
zx

array([[12, 34, 45, 67, 45, 23],
       [45, 56, 23, 56, 23, 23]])

In [18]:
zx.ndim

2

In [19]:
zx = np.array([[12, 34, 45, 67, 45, 23], [45, 56, 23, 56, 23, 23]])

In [20]:
np.reshape(zx, (12))

array([12, 34, 45, 67, 45, 23, 45, 56, 23, 56, 23, 23])

In [21]:
# -1

In [22]:
zx = np.array([[12, 34, 45, 67, 45, 23], [45, 56, 23, 56, 23, 23]])

In [23]:
zx

array([[12, 34, 45, 67, 45, 23],
       [45, 56, 23, 56, 23, 23]])

In [24]:
np.reshape(zx, -1)

array([12, 34, 45, 67, 45, 23, 45, 56, 23, 56, 23, 23])

In [25]:
# 1-D to 2-D

In [33]:
arr = np.array([12, 34, 45, 56, 78, 45, 34, 56, 23, 34, 657, 45])

In [35]:
np.reshape(arr, (4, -1))

array([[ 12,  34,  45],
       [ 56,  78,  45],
       [ 34,  56,  23],
       [ 34, 657,  45]])