In [1]:
print("hello word")

hello word


In [2]:
a = 10
b = 20

In [3]:
c = a + b

In [4]:
print(c)

30


In [5]:
c

30

In [ ]:
jupyter notebook .

python -m notebook .

# Numpy

## Numpy

### Numpy

In [ ]:
Numpy : Numarical Python

In [9]:
# Arrays ----

# List
# Tuple
# Set
# Dectionry

In [ ]:
1991

2005 ---> Numpy
         Travis Oliphant

In [ ]:
List

[12, 34, "helo", True, "no"]

Array => collection of mutiple data, or data must of homogenious(same type of data).

Numpy (Array)

    1) Numpy
        70%   -> C/C#
        30%   -> Python

    2) Array Store Homogenious Data

In [ ]:
# Numpy : 
#     Arrays 
#         Dimmensions 

In [10]:
!pip install numpy

DEPRECATION: textract 1.6.5 has a non-standard dependency specifier extract-msg<=0.29.*. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of textract or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063


In [11]:
import numpy as np

#### ndarrays : 
#### when we create an obejct with the help of array method in numpy, that object  is called ndarray.

In [12]:
x = np.array(100)

In [15]:
type(x)

numpy.ndarray

In [13]:
y = 20

In [14]:
type(y)

int

In [16]:
x = np.array(100)

In [17]:
x

array(100)

In [18]:
y = np.array([12, 34, 5, 67])

In [19]:
y

array([12, 34,  5, 67])

In [20]:
y = np.array([[12, 34, 5, 67], [45, 67, 78, 657]])

In [21]:
y

array([[ 12,  34,   5,  67],
       [ 45,  67,  78, 657]])

In [22]:
# 0-D

In [23]:
arr1 = np.array(20)

In [ ]:
ndim (attribute): to check the demmensions of an ndarray

shape : it return shape of an ndarray.

In [24]:
arr1.ndim

0

In [25]:
arr1.shape

()

In [26]:
# 1-D nddary

In [27]:
arr2 = np.array([12, 34, 45, 67, 89])

In [28]:
arr2

array([12, 34, 45, 67, 89])

In [29]:
arr2.shape

(5,)

In [30]:
arr2.ndim

1

In [31]:
# Ndarray : combination of multiple 1-D ndarrays

In [36]:
arr3 = np.array([[12, 34, 56, 67], [34, 56, 7, 89], [34, 5, 67, 34]])

In [37]:
arr3

array([[12, 34, 56, 67],
       [34, 56,  7, 89],
       [34,  5, 67, 34]])

In [38]:
arr3.ndim

2

In [39]:
arr3.shape

(3, 4)

In [43]:
hey = np.array([[45, 56, 78], [34, 56, 56]])

In [44]:
hey

array([[45, 56, 78],
       [34, 56, 56]])

In [45]:
hey.shape

(2, 3)

### 3-D ndarry : combination of multiple 2-d nd arrays

In [59]:
arr4 = np.array([[[23, 34, 56], [34, 45, 6]], [[45, 56, 67], [45, 56, 34]]])

In [60]:
arr4

array([[[23, 34, 56],
        [34, 45,  6]],

       [[45, 56, 67],
        [45, 56, 34]]])

In [61]:
arr4.ndim

3

In [62]:
arr4.shape

(2, 2, 3)

In [52]:
# x = (23, )

In [54]:
# type(x)

In [65]:
# zx = np.array([[[[[[[[[[78]]]]]]]]]])

In [66]:
# zx.ndim