In [1]:
# Numpy:

In [2]:
import numpy as np

In [7]:
# append() : -> joining two ndarrays

In [8]:
x = np.array([12, 45, 56, 67, 23, 100])

In [9]:
y = np.array([45, 67, 3, 56, 23, 100])

In [10]:
np.append(x, y)

array([ 12,  45,  56,  67,  23, 100,  45,  67,   3,  56,  23, 100])

In [11]:
# 

In [12]:
# trim_zeros()

In [13]:
zx = np.array([0, 0, 56, 78, 45, 0, 67, 0, 23, 1, 0, 0, 0])

In [14]:
np.trim_zeros(zx)

array([56, 78, 45,  0, 67,  0, 23,  1])

In [15]:
# unique()

In [16]:
x = np.array([12, 34, 45, 23, 12, 23, 45, 23, 56, 78, 34, 12, 34, 23, 100])

In [17]:
np.unique(x)

array([ 12,  23,  34,  45,  56,  78, 100])

In [18]:
# st = {12, 34, 45, 23, 12, 23, 45, 23, 56, 78, 34, 12, 34, 23, 100}

In [20]:
# st

In [21]:
# zeros()

In [25]:
data = np.zeros((3, 4))

In [26]:
data

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
# ones()

In [30]:
xyz = np.ones((5, 7))

In [31]:
xyz

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [32]:
help(np.diagonal)

Help on _ArrayFunctionDispatcher in module numpy:

diagonal(a, offset=0, axis1=0, axis2=1)
    Return specified diagonals.

    If `a` is 2-D, returns the diagonal of `a` with the given offset,
    i.e., the collection of elements of the form ``a[i, i+offset]``.  If
    `a` has more than two dimensions, then the axes specified by `axis1`
    and `axis2` are used to determine the 2-D sub-array whose diagonal is
    returned.  The shape of the resulting array can be determined by
    removing `axis1` and `axis2` and appending an index to the right equal
    to the size of the resulting diagonals.

    In versions of NumPy prior to 1.7, this function always returned a new,
    independent array containing a copy of the values in the diagonal.

    In NumPy 1.7 and 1.8, it continues to return a copy of the diagonal,
    but depending on this fact is deprecated. Writing to the resulting
    array continues to work as it used to, but a FutureWarning is issued.

    Starting in NumPy 1.9 it r

In [35]:
np.diagonal()

ValueError: diag requires an array of at least two dimensions

In [39]:
x = np.array([[34, 54, 12], [56, 34, 23], [56, 34, 23]])

In [40]:
x

array([[34, 54, 12],
       [56, 34, 23],
       [56, 34, 23]])

In [41]:
x.diagonal()

array([34, 34, 23])

In [ ]:
questions:

1) x = 8129308927002394092340900070394

ex:
x = 10210201101

output:
totle number of zeros :4
the sum of 1, 2, 1, 2, 1, 1, 1 is : 9

In [ ]:
x = 5
output: 543212345

x = 6
65432123456

x = 3
32123