In [1]:
# numpy : 


In [2]:
import numpy as np

In [3]:
# list:

# 1) ordered
# 2) allow duplicate values
# 3) Mutable 

In [5]:
zx = np.array([12, 34, 23, 100, 67, 100])

In [6]:
# lst = [1, 5, 2, 5, 8]


In [7]:
lst.append(1000)

In [8]:
lst

[1, 5, 2, 5, 8, 1000]

In [9]:
zx = np.array([12, 34, 23, 100, 67, 100])

In [10]:
# numpy.append(objectname, items)

In [11]:
zx

array([ 12,  34,  23, 100,  67, 100])

In [12]:
np.append(zx, 2000)

array([  12,   34,   23,  100,   67,  100, 2000])

In [13]:
zx = np.array([12, 34, 23, 100, 67, 100])

In [14]:
zx

array([ 12,  34,  23, 100,  67, 100])

In [15]:
lst = [12, 45, 23, 56, 100]

In [16]:
np.append(zx, lst)

array([ 12,  34,  23, 100,  67, 100,  12,  45,  23,  56, 100])

### replace elements//

In [17]:
x = np.array([45, 3230, 45, 2, 3, 1, 100, 4, 10, 67, 34])

In [ ]:
# objname[indexnumber] = newitem

In [18]:
x[1] = 32

In [19]:
x

array([ 45,  32,  45,   2,   3,   1, 100,   4,  10,  67,  34])

In [20]:
x[-2] = 1000

In [21]:
x

array([  45,   32,   45,    2,    3,    1,  100,    4,   10, 1000,   34])

In [22]:
qww = np.array([1, 2, 3, 4, 5, 6, 7, 8, 10])

In [23]:
indexs = [1, 5, -2]

In [24]:
ele = [100, 200, 300]

In [25]:
qww[indexs] = ele

In [26]:
qww

array([  1, 100,   3,   4,   5, 200,   7, 300,  10])

In [27]:
# insert 

In [28]:
lst = [1, 3, 4, 6, 10, 90, 4]

In [29]:
lst.append(20)

In [30]:
lst

[1, 3, 4, 6, 10, 90, 4, 20]

In [31]:
lst.insert(1, 200)

In [32]:
lst

[1, 200, 3, 4, 6, 10, 90, 4, 20]

### insert in numpy

In [33]:
x = np.array([4, 3, 5, 2, 6, 8, 3, 10])

In [35]:
np.insert(x, 2, 300)

array([  4,   3, 300,   5,   2,   6,   8,   3,  10])

In [37]:
# appned()
# insert()

# replacing elements:::::::

In [38]:
# zx = .....

In [39]:
# [1, 2, 3, 4, 5, 6, 7 ..... 50]

In [ ]:
# ["2 x 1 = 2", "2 x 2 = 4", "2 x 3 = 6" .........]

In [ ]:
# import numpy as np

In [47]:
xyz = np.array([])

for i in range(1, 51):
    xyz = np.append(xyz, i)

In [48]:
xyz

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [49]:
# ["2 x 1 = 2", "2 x 2 = 4", "2 x 3 = 6" .........]

In [54]:
x = np.array([])

for i in range(10, 0, -1):
    # print(f"2 x {i} = {2*i}")
    x = np.append(x, f"2 x {i} = {2*i}")

In [55]:
x

array(['2 x 10 = 20', '2 x 9 = 18', '2 x 8 = 16', '2 x 7 = 14',
       '2 x 6 = 12', '2 x 5 = 10', '2 x 4 = 8', '2 x 3 = 6', '2 x 2 = 4',
       '2 x 1 = 2'], dtype='<U32')