In [1]:
# Numpy : 

In [2]:
# ndarrys : 

### Nummpy indexin or slicing::::

In [4]:
import numpy as np

arr = np.array([[12, 4, 23, 56, 100], [45, 67, 34, 23, 45]])

In [5]:
arr

array([[ 12,   4,  23,  56, 100],
       [ 45,  67,  34,  23,  45]])

In [6]:
arr.ndim

2

In [7]:
# indexing:::::

In [9]:
arr = np.array([12, 4, 23, 56, 100, 100, 5, 2, 3, 100])

In [10]:
arr

array([ 12,   4,  23,  56, 100, 100,   5,   2,   3, 100])

In [11]:
# objectname[indexnumber]

In [13]:
arr[3] + arr[8]

59

In [14]:
# negtive indexing.....

In [15]:
arr[-3]

2

In [16]:
# indexing with 2d

In [17]:
arr = np.array([[12, 4, 23, 56, 100], [34, 56, 34, 23, 12]])

In [18]:
arr

array([[ 12,   4,  23,  56, 100],
       [ 34,  56,  34,  23,  12]])

In [19]:
# lst = [23, 45, 23, 100, [45, 200, 45, 23, 10], 67, [23, 45]]

In [23]:
# lst[4][1]

In [30]:
arr = np.array([[12, 4, 23, 56, 100], [34, 560, 34, 23, 12]])

In [33]:
arr[1][1]

560

In [34]:
xy = np.array([[45, 34, 2, 5, 100], [78, 45, 34, 33, 22], [100, 400, 569, 300, 90]])

In [36]:
xy[2][1]

400

In [37]:
xy[0][3]

5

In [38]:
xy = np.array([[[45, 34, 2, 5, 100], [78, 45, 34, 33, 22]], [[100, 400, 569, 300, 90], [56, 34, 23, 1000, 56]]])

In [39]:
xy

array([[[  45,   34,    2,    5,  100],
        [  78,   45,   34,   33,   22]],

       [[ 100,  400,  569,  300,   90],
        [  56,   34,   23, 1000,   56]]])

In [43]:
xy[1][1][3]

1000

In [44]:
xy[0][1][3]

33

In [45]:
# slicing:::::::

In [ ]:
objename[start : end : increment]

In [ ]:
default:
 start === 0
 end ==== n - 1
 increment === 1

In [46]:
zx = np.array([34, 100, 3, 1, 100, 45, 23, 100])

In [47]:
zx[1 : 6]

array([100,   3,   1, 100,  45])

In [51]:
# zx[3 : 7 : 2]

In [ ]:
objename[start : end : increment]

In [52]:
zx[1 : ]

array([100,   3,   1, 100,  45,  23, 100])

In [53]:
zx[: 4]

array([ 34, 100,   3,   1])

In [54]:
zx = np.array([34, 100, 3, 1, 100, 45, 23, 100])

In [55]:
zx[: : -1]

array([100,  23,  45, 100,   1,   3, 100,  34])

In [57]:
# with 2d

In [58]:
xy = np.array([[45, 34, 2, 5, 100], [78, 45, 34, 33, 22], [100, 400, 569, 300, 90]])

In [60]:
xy[1][1 : ]

array([45, 34, 33, 22])