In [1]:
# Numpy : 

In [2]:
# ndarray : 

In [3]:
import numpy as np

In [ ]:
ndarray
# where()
ndim
shape
slicing/ indexing


In [5]:
zx = np.array([[12, 34, 45, 23, 45], [67, 56, 23, 21, 34]])

In [6]:
zx

array([[12, 34, 45, 23, 45],
       [67, 56, 23, 21, 34]])

In [7]:
zx.ndim

2

In [8]:
# where() 
    

In [9]:
zx = np.array([[12, 34, 45, 23, 45], [67, 56, 23, 21, 34]])

zx[0][1]

### where() --> help us to get index number fo  a perticuler elemnt/item

In [15]:
qw = np.array([34, 56, 34, 23, 45, 23, 34, 23, 56, 78, 34, 56, 3, 100, 23])

In [14]:
np.where(qw == 45)

(array([4], dtype=int64),)

In [16]:
np.where(qw == 23)

(array([ 3,  5,  7, 14], dtype=int64),)

In [17]:
# sort() ----> 

In [18]:
qw = np.array([34, 56, 34, 23, 45, 23, 34, 23, 56, 78, 34, 56, 3, 100, 23])

In [24]:
op = np.sort(qw[::-1])

In [25]:
op

array([  3,  23,  23,  23,  23,  34,  34,  34,  34,  45,  56,  56,  56,
        78, 100])

In [26]:
op[: : -1]

array([100,  78,  56,  56,  56,  45,  34,  34,  34,  34,  23,  23,  23,
        23,   3])

In [27]:
# arange()  ---->  

In [28]:
# xyz = np.arange(start, ending, increment)

default:
    start == 0
    end === n - 1
    incremnt = 1

In [29]:
xyz = np.arange(1, 21, 1)

In [30]:
xyz

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [31]:
type(xyz)

numpy.ndarray

In [32]:
# 9 ---- 2

In [37]:
pqr = np.arange(9, 1, -1)

In [38]:
pqr

array([9, 8, 7, 6, 5, 4, 3, 2])

In [ ]:
where()
arange()
sort()

In [40]:
# reshape() 

## 1d to 2d

In [43]:
x = np.array([12, 34, 23, 56, 34, 68, 44, 23, 7, 100])

In [44]:
x.ndim

1

In [53]:
p = x.reshape(2, 5)

In [54]:
p.ndim

2

In [55]:
p

array([[ 12,  34,  23,  56,  34],
       [ 68,  44,  23,   7, 100]])

In [56]:
p.shape

(2, 5)

In [57]:
# -1

In [60]:
zx = np.array([45, 34, 23, 45, 67, 34, 2, 89, 7, 34, 23, 100, 90, 78, 45])

In [61]:
zx.reshape(3, -1)

array([[ 45,  34,  23,  45,  67],
       [ 34,   2,  89,   7,  34],
       [ 23, 100,  90,  78,  45]])

In [62]:
zx.reshape(-1, 3)

array([[ 45,  34,  23],
       [ 45,  67,  34],
       [  2,  89,   7],
       [ 34,  23, 100],
       [ 90,  78,  45]])

## 2d -- 1d

In [63]:
zx = np.array([[4, 7, 34, 23, 45, 23, 45], [45, 567, 34, 23, 2, 34, 100]])

In [64]:
zx.ndim

2

In [65]:
zx

array([[  4,   7,  34,  23,  45,  23,  45],
       [ 45, 567,  34,  23,   2,  34, 100]])

In [66]:
new = zx.reshape(-1)

In [67]:
new

array([  4,   7,  34,  23,  45,  23,  45,  45, 567,  34,  23,   2,  34,
       100])

In [68]:
new.ndim

1

### 1d to 3d

In [75]:
zx = np.array([45, 34, 23, 45, 23, 112, 34, 78, 56, 45, 78, 4, 2, 100, 56, 100, 90, 67])

In [76]:
len(zx)

18

In [77]:
zx.reshape(3, 3, 2)

array([[[ 45,  34],
        [ 23,  45],
        [ 23, 112]],

       [[ 34,  78],
        [ 56,  45],
        [ 78,   4]],

       [[  2, 100],
        [ 56, 100],
        [ 90,  67]]])

In [78]:
# random

In [79]:
zx = ["this is a car"]

In [ ]:
output : ["this", "is", "a", "car"]