In [1]:
# Numpy : 

# numpy
# pandas
# matplotlib

In [2]:
# Numpy : numarical python...

# arrays

# array ------ list 

In [3]:
zx = [12, 100, 78, 45, 9000]

In [4]:
# list   vs   tuple 

In [5]:
# numpy ------>

In [6]:
lst = [10, 45, "heloo", True, 100.8]

In [7]:
type(lst)

list

In [8]:
# numpy 

# zx = [10, 45, 23, 100, 67]

# 50x

In [9]:
# numpy : 

# 70% python
# 30% c/ c++

In [10]:
!pip install numpy

DEPRECATION: textract 1.6.5 has a non-standard dependency specifier extract-msg<=0.29.*. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of textract or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063


In [13]:
import numpy as np

## ndarrays

In [ ]:
ndarrays : n dimatioanl arrayy

ndarrays : while in numpy we craete an object with the help of array method, that object is called ndarray...

In [19]:
ar = np.array(100)

In [15]:
ar

array(100)

In [16]:
type(ar)

numpy.ndarray

In [17]:

a = 10

In [18]:
type(a)

int

In [20]:
# arrays : 

In [21]:
ar = np.array(100)

###  ndim : to check the dimmensions of an ndarray

In [22]:
# objename.ndim


ar.ndim

0

In [23]:
xyz = np.array([12, 10, 78, 100])

In [24]:
xyz

array([ 12,  10,  78, 100])

In [25]:
xyz.ndim

1

## crate 2d ndarray

In [30]:
arr2 = np.array([[12, 10, 90, 100], [34, 100, 56, 23]])

In [31]:
arr2

array([[ 12,  10,  90, 100],
       [ 34, 100,  56,  23]])

In [32]:
arr2.ndim

2

In [36]:
pqr = np.array([[12, 45, 23, 100, 90], [45, 23, 12, 56, 23], [45, 34, 23, 56, 23]])

In [37]:
pqr

array([[ 12,  45,  23, 100,  90],
       [ 45,  23,  12,  56,  23],
       [ 45,  34,  23,  56,  23]])

In [38]:
pqr.ndim

2

In [ ]:
array() --> to genrate ndarrays

attribues:
    ndim ---> return dimmesions of an ndarray
    

### shape :::: it return the shape of an ndarray ...
### return number of rows and number of columns...

In [39]:
pqr = np.array([[12, 45, 23, 100, 90], [45, 23, 12, 56, 23], [45, 34, 23, 56, 23]])

In [40]:
pqr

array([[ 12,  45,  23, 100,  90],
       [ 45,  23,  12,  56,  23],
       [ 45,  34,  23,  56,  23]])

In [41]:
pqr.shape

(3, 5)

In [44]:
qw = np.array([34, 23, 100, 45])

In [45]:
qw.shape

(4,)

In [ ]:
array() --> to genrate ndarrays

attribues:
    ndim ---> return dimmesions of an ndarray
    shape ---> it retunns number of rows and number of colmnss

### create 3d ndarray :::::::::::::::

In [54]:
arrx = np.array([[[12, 56, 34], [45, 56, 34]], [[45, 34, 23], [45, 23, 10]]])

In [55]:
arrx

array([[[12, 56, 34],
        [45, 56, 34]],

       [[45, 34, 23],
        [45, 23, 10]]])

In [56]:
arrx.ndim

3

In [57]:
arrx.shape

(2, 2, 3)