In [1]:
# Numpy : 

In [2]:
# ndarrays --->

In [3]:
# random:

In [4]:
import numpy as np

In [5]:
xyz = np.array([12, 45, 23, 67, 100, 20])

In [6]:
xyz.ndim

1

In [7]:
xyz

array([ 12,  45,  23,  67, 100,  20])

In [8]:
abc = np.array([[23, 45, 100, 90], [67, 45, 23, 100], [78, 45, 34, 23]])

In [9]:
abc

array([[ 23,  45, 100,  90],
       [ 67,  45,  23, 100],
       [ 78,  45,  34,  23]])

In [10]:
abc.ndim

2

In [11]:
# where()

In [ ]:
# import random

In [13]:
from numpy import random

In [29]:
random.randint(100)

46

## genrating 1-D ndarray random

In [31]:
xy = random.randint(100, size = (5))

In [32]:
xy

array([50, 14, 95, 28, 85])

In [33]:
type(xy)

numpy.ndarray

In [34]:
xy.ndim

1

In [35]:
xy.shape

(5,)

In [38]:
# zx = (10, )

In [40]:
# type(zx)

## 2-d ndarry::::

In [47]:
p = random.randint(50, size = (3, 5))

In [49]:
p

array([[11, 26, 32, 49,  7],
       [35, 35,  8, 12,  0],
       [46, 48, 18,  2, 11]])

In [51]:
# help(random.rand)

In [52]:
# rand() ------> 0, 1

### rand() --> return elments with the range of 0 to 1

In [61]:
x = random.rand(4, 3)

In [62]:
x

array([[0.67292762, 0.79573907, 0.00967793],
       [0.39498833, 0.20433648, 0.64546437],
       [0.56804355, 0.83308742, 0.30501592],
       [0.521006  , 0.71150226, 0.13056765]])

In [63]:
# choice() --> 

In [78]:
zx = random.choice([34, 56, 23, 67, 100, 87], size = (2, 5))

In [79]:
zx

array([[56, 23, 34, 23, 34],
       [67, 56, 23, 56, 23]])

In [ ]:
## 

# np.arange()

genrate --- 1 to 100

[1, 2, 3, 4, 5, ........ 100]


3 -devisible--> ok
5 --devisible---> done
 0.
3 or 5 ----> okdone

In [ ]:
[1, 2, "ok", 4, "done", "ok", 7, 8, "ok", ....., "okdone"]

In [86]:
x = int(input("Enter the range : "))

myarr = np.arange(1, x+1)


Enter the range :  50


In [87]:
myarr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [99]:
zx = np.array([])

In [100]:
for i in myarr:
    if i % 3 == 0:
        zx = np.append(zx, "ok")
    elif i % 5 == 0:
        zx = np.append(zx, "done")
    elif i % 3 == 0 and i % 5 == 0:
        zx = np.append(zx, "okdone")
    else:
        zx = np.append(zx, i)

In [101]:
zx

array(['1.0', '2.0', 'ok', '4', 'done', 'ok', '7', '8', 'ok', 'done',
       '11', 'ok', '13', '14', 'ok', '16', '17', 'ok', '19', 'done', 'ok',
       '22', '23', 'ok', 'done', '26', 'ok', '28', '29', 'ok', '31', '32',
       'ok', '34', 'done', 'ok', '37', '38', 'ok', 'done', '41', 'ok',
       '43', '44', 'ok', '46', '47', 'ok', '49', 'done'], dtype='<U32')